#!/bin/sh
#. "$(dirname "$0")/_/husky.sh"

echo "🔍 Type checking..."
yarn tsc --noEmit
if [ $? -ne 0 ]; then
  echo "❌ Type check failed. Commit aborted."
  exit 1
fi

echo "🧹 Lint checking..."
yarn lint
if [ $? -ne 0 ]; then
  echo "❌ Lint failed. Commit aborted."
  exit 1
fi

echo "✅ Pre-commit checks passed!"