#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# 예: feat: ~, fix: ~ 형식만 허용
if ! echo "$commit_msg" | grep -Eq "^(feat|fix|chore|docs|refactor|style)\: .+"
then
  echo "❌ 커밋 메시지는 다음 형식을 따라야 합니다:"
  echo "   예) feat: 로그인 기능 추가"
  exit 1
fi