name: Chromatic

on:
  pull_request:
    branches: [develop]
    paths:
      - '**/*.stories.tsx'
  push:
    branches: [develop]
    paths:
      - '**/*.stories.tsx'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-storybook

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Comment PR with Storybook link
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: '🚀 Storybook URL: ${{ steps.chromatic.outputs.storybookUrl }}'
